/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SPScene(props) {
    const { nodes, materials } = useGLTF('/spScene.glb')
    return (
        <group {...props} dispose={null}>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.jambes001.geometry}
            material={materials.pant}
            position={[0, 0.044, 6.078]}
            scale={0.001}
        />
        <group position={[0, 0.044, 6.078]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.pied_right001_1.geometry}
            material={materials.shoes}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.pied_right001_2.geometry}
            material={materials['shoes_bt.001']}
            />
        </group>
        <group position={[0, 0.044, 6.078]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.pied_left001_1.geometry}
            material={materials.shoes}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.pied_left001_2.geometry}
            material={materials.shoes_bt}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.smile001.geometry}
            material={materials['wire_027177027.007']}
            position={[0, 0.044, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.oeil_right001.geometry}
            material={materials['eye-white']}
            position={[0, 0, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.oeil_left001.geometry}
            material={materials['eye-white']}
            position={[0, 0, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.iris_L001.geometry}
            material={materials.eye_black}
            position={[0, 0, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.barbe001.geometry}
            material={materials.chevelure}
            position={[0, 0.044, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.coiffure001.geometry}
            material={materials.chevelure}
            position={[0, 0.044, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.bouton1001.geometry}
            material={materials['wire_006135113.007']}
            position={[0.019, 0.044, 6.052]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.broncos_patch001.geometry}
            material={materials['Material__34.007']}
            position={[0.019, 0.044, 6.052]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.corp001.geometry}
            material={materials.body}
            position={[0, 0.044, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.panneau_stick.geometry}
            material={materials.pannel_stick}
            position={[-0.788, 0, 5.569]}
            scale={0.001}
        />
        <group position={[-0.788, 0, 5.569]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.panneau_top001_1.geometry}
            material={materials.pannel_front}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.panneau_top001_2.geometry}
            material={materials.pannel_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree001001.geometry}
            material={materials['wire_154185229.007']}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree002001.geometry}
            material={materials['wire_154185229.007']}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree003001.geometry}
            material={materials['wire_154185229.007']}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree004001.geometry}
            material={materials['wire_154185229.007']}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree005001.geometry}
            material={materials['wire_154185229.007']}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree006001.geometry}
            material={materials['wire_154185229.007']}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tree007001.geometry}
            material={materials['wire_154185229.007']}
            position={[0, 0, -1.118]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.background001.geometry}
            material={materials['wire_140088225.007']}
            position={[0, 0.043, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere040002.geometry}
            material={materials.skin}
            position={[0, 0.044, 6.078]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.iris_L001001.geometry}
            material={materials.eye_black}
            position={[0, 0, 6.078]}
            scale={0.001}
        />
        <group position={[21.877, 0, -2.576]} rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.javascript002_1.geometry}
            material={materials.js}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.javascript002_2.geometry}
            material={materials.js_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_2001.geometry}
            material={materials.snow}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_4001.geometry}
            material={materials.snow}
            position={[21.877, 0, -2.576]}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_005001.geometry}
            material={materials.snow}
            position={[4.202, 0, 0]}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group position={[4.202, 0, 0]} rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.react002_1.geometry}
            material={materials['react.001']}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.react002_2.geometry}
            material={materials['react_sides.001']}
            />
        </group>
        <group position={[0, 0.043, 0]} rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.typescript002_1.geometry}
            material={materials.ts}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.typescript002_2.geometry}
            material={materials.ts_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_008001.geometry}
            material={materials.snow}
            position={[-1.455, 0, 2.284]}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.threeJs001.geometry}
            material={materials.three}
            position={[-1.455, 0, 2.284]}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_010001.geometry}
            material={materials.snow}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.mongodb002_1.geometry}
            material={materials['mongodb.001']}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.mongodb002_2.geometry}
            material={materials.mongodb_sides}
            />
        </group>
        <group position={[-35.107, 0, -0.853]} rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.nodejs002_1.geometry}
            material={materials.node}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.nodejs002_2.geometry}
            material={materials.node_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_012001.geometry}
            material={materials.snow}
            position={[-35.107, 0, -0.853]}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group position={[3.073, 0, -4.498]} rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.css002_1.geometry}
            material={materials.css}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.css002_2.geometry}
            material={materials.css_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_014.geometry}
            material={materials.snow}
            position={[3.073, 0, -4.498]}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.html002_1.geometry}
            material={materials.html}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.html002_2.geometry}
            material={materials.html_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_015.geometry}
            material={materials.snow}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.sql002_1.geometry}
            material={materials.sql}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.sql002_2.geometry}
            material={materials.sql_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_016.geometry}
            material={materials.snow}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group position={[6.805, 0, 0]} rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.tailwind002_1.geometry}
            material={materials.tailwind}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.tailwind002_2.geometry}
            material={materials['tailwind_sides.001']}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_017.geometry}
            material={materials.snow}
            position={[6.805, 0, 0]}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.toshop001_1.geometry}
            material={materials.toshop}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.toshop001_2.geometry}
            material={materials.toshop_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_018.geometry}
            material={materials.snow}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.snowBall_019.geometry}
            material={materials.snow}
            rotation={[0.001, 0, 0]}
            scale={0.001}
        />
        <group rotation={[0.001, 0, 0]} scale={0.001}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.nextjs002_1.geometry}
            material={materials.next}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.nextjs002_2.geometry}
            material={materials.next_sides}
            />
        </group>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.fence.geometry}
            material={materials.wire_057008136}
            position={[0, -0.264, 0]}
            rotation={[-0.018, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.trotoir.geometry}
            material={materials.concrete}
            position={[0, 7.561, 15.593]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.sol003.geometry}
            material={materials.neige}
            rotation={[-0.008, 0, 0]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.bouton1002.geometry}
            material={materials['wire_006135113.001']}
            position={[0.106, -0.194, 6.139]}
            scale={0.001}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.bouton1003.geometry}
            material={materials['wire_006135113.002']}
            position={[0.196, -0.451, 6.21]}
            scale={0.001}
        />
        </group>
    )
}

useGLTF.preload('/spScene.glb')

